#
# Filter setting for intranet environment.
# This setting is used by default.
# For details, check http://docs.asakusa-satellite.org/
#

info:
 version: 2

filters:
 - name: code_highlight_filter
 - name: auto_link
 - name: emoji_filter
 - name: jira_ticket_link

plugins:
 - dir: as_desktopnotification
 - dir: as_global_js_css
 - dir: as_notification_area_plugin
 - dir: as_room_list_plugin
 - dir: as_online_status
 - dir: as_direct_message_plugin
 - dir: as_omniauth_crowd_plugin
 - dir: as_profile_setting
 - dir: as_global_js_css
