omniauth:
  provider: "crowd"
  provider_args:
    crowd_server_url: "http://10.5.5.29/itscrowd"
    application_name: "asakusasatellite"
    application_password: "Asakusa"

#crowd_server_url: "http://10.5.5.24:8095/itscrowd"

# file attachment
attachment_policy: <%= ENV['SETTINGS_ATTACHMENT_POLICY'] || "local" %>
attachment_path: <%= ENV['SETTINGS_ATTACHMENT_PATH'] || "public/upload" %>
attachment_max_size: <%= ENV['SETTINGS_ATTACHMENT_MAX_SIZE'] %>
watage_token: <%= ENV['SETTINGS_WATAGE_ACCESS_TOKEN'] || "00000000-0000-0000-0000-000000000000" %>
watage_token_secret: <%= ENV['SETTINGS_WATAGE_ACCESS_TOKEN_SECRET'] || "00000000-0000-0000-0000-000000000000" %>
